### ISSUE TITLE
SQL preview fails on Theme Change

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [PRQL/prql-vscode#27] opened 2023-01-05 11:03 UTC
It seems to get stuck in loading when the color theme is changed

**Comment by jiripospisil** [comment] 2023-01-05 13:56
Works for me. Does it happen every time?

https://user-images.githubusercontent.com/20820/210796587-0192fa86-a0da-485b-8213-bfe03d96f4ea.mp4

**Comment by jiripospisil** [comment] 2023-01-16 09:37
Closing for now. Please reopen if you have reproduction steps. Thank you!

**Closed by jiripospisil** 2023-01-16 09:37 UTC
